version: "3.8"
services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-ci-demo
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
      - "CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./demo-repo:/demo-repo
    restart: unless-stopped

  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "6000:5000"
    restart: unless-stopped

volumes:
  jenkins_home:
